version: '3.3'

services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile.db
    ports:
      - 5432:5432
    networks:
      - app_net

  redis:
    image: redis:alpine
    networks:
      - app_net

  sqli:
    build:
      context: .
      dockerfile: Dockerfile.app
    depends_on:
      - postgres
      - redis
    ports:
      - 8080:8080
    command: |
      wait-for postgres:5432 -- python run.py
    networks:
      - app_net

  zaproxy:
    image: ghcr.io/zaproxy/zaproxy:stable
    networks:
      - app_net
      
networks:
  app_net:
    name: app_net
    driver: bridge